# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_id', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_id', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='team.Team'),
        ),
    ]
