# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20161001_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='away_id',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='home_id',
            new_name='home',
        ),
    ]
