# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20161001_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='away',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='result',
        ),
    ]
