# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('matches', '0009_auto_20161001_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='away',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='team.Team'),
            preserve_default=False,
        ),
    ]
