# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_matches_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='team.Team'),
        ),
    ]
