# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_coach'),
        ('matches', '0013_auto_20161001_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='result_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='match_result', to='team.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
