# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_info',
        ),
    ]
