# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_card',
            field=models.IntegerField(default=0),
        ),
    ]
