# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20161106_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='matches',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
