# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_team_matches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='matches',
            new_name='points',
        ),
    ]
